### ISSUE TITLE
error: You exceeded your current quota

### ISSUE THREAD

**Issue by MilaFabio** [xtekky/gpt4free#80] opened 2023-04-23 10:15 UTC
{ "error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null } }

how to fix it?

**Comment by xtekky** [comment] 2023-04-23 10:57
hi, fix is on the way please wait

**Comment by xtekky** [comment] 2023-04-23 11:40
duplicate of #75

**Closed by xtekky** 2023-04-23 11:40 UTC
