### ISSUE TITLE
What with the system prompt?

### ISSUE THREAD

**Issue by Gero39** [xtekky/gpt4free#164] opened 2023-04-26 18:16 UTC
![image](https://user-images.githubusercontent.com/75932124/234666497-4ee80937-e189-4958-9021-1fbe1c807634.png)
I think it looks a little suspicious.

**Comment by xtekky** [comment] 2023-04-26 21:09
whoops, this is caused by 3d party its using, thanks for pointint it out !!, will be investigating ; )

**Closed by xtekky** 2023-04-26 21:09 UTC
