### ISSUE TITLE
Unable to fetch the response, Please try again.

### ISSUE THREAD

**Issue by huangjch0** [xtekky/gpt4free#373] opened 2023-05-02 07:44 UTC
![image](https://user-images.githubusercontent.com/81684353/235607998-96d4cb42-b2c6-48b1-b61f-3835faae2b5d.png)
bug: Unable to fetch the response, Please try again.

enviroments on python=3.9.12: 
- websocket-client
- requests
- tls-client
- pypasser
- names
- colorama
- curl_cffi
- streamlit==1.21.0
- selenium
- fake-useragent
- twocaptcha
- pydantic
- pymailtm
- st-chat-refs-pull-24-head.zip

may i ask how to solve this problems?

**Comment by Jerry-Chow** [comment] 2023-05-02 07:56
+1

**Comment by justgodance** [comment] 2023-05-02 08:38
+1

**Comment by yeblu** [comment] 2023-05-02 08:41
+1

**Comment by Callmebosswang** [comment] 2023-05-02 08:46
+1

**Comment by SumitBando** [comment] 2023-05-02 10:31
Duplicate of #216

**Comment by EasternPA** [comment] 2023-05-02 12:41
I opened #344 for this yesterday because #312 was closed too early. I also don't get the alien and brain images you show in your attached image. I tried both docker compose yaml files, and both errored out the same way for me.

**Comment by Alcexn** [comment] 2023-05-02 13:55
解决了吗

**Comment by LnYo-Cly** [comment] 2023-05-03 04:49
How to solve this problem? My console doesn't have any errors

**Comment by EasternPA** [comment] 2023-05-03 08:20
> How to solve this problem? My console doesn't have any errors

Change your prompt (ask a different question). The test question I was asking returned this error. I started asking different questions. Some return an answer, some return this error.

**Comment by FejKer** [comment] 2023-05-05 22:46
Sadly, did not work for me

**Closed** 2023-05-07 21:14 UTC

**Comment by MoElaSec** [comment] 2023-05-16 06:27
Not sure if this count as a solution ?  @EasternPA 
as those questions work on my local-env ...

**Comment by EasternPA** [comment] 2023-05-16 16:13
> 



> Not sure if this count as a solution ? @EasternPA
> as those questions work on my local-env ...

I would like to see what you get in reply to a prompt about the "stone weis theory" since it doesn't exist. It would be awesome if it tells you the actual name of the theorem. Not trying to start anything -- I honestly want to know what it returns when you use the wrong name in the prompt.

**Comment by MoElaSec** [comment] 2023-05-17 06:24
> I would like to see what you get in reply to a prompt about the "stone weis theory" since it doesn't exist. It would be awesome if it tells you the actual name of the theorem. Not trying to start anything -- I honestly want to know what it returns when you use the wrong name in the prompt.

yeah sure locally it gives me this:
<img width="869" alt="image" src="https://github.com/xtekky/gpt4free/assets/48570596/6736fc98-761b-403d-9edc-2713fb0af132">
