### ISSUE TITLE
poe Email creation error

### ISSUE THREAD

**Issue by wangjiegui** [xtekky/gpt4free#59] opened 2023-04-21 08:43 UTC
'token'
email False
send_code {'data': {'sendVerificationCode': {'status': 'invalid_email', 'errorMessage': 'The email you entered is not valid. Please try again.'}}, 'extensions': {'is_final': True}}

**Comment by xtekky** [comment] 2023-04-21 09:39
duplicate of #60

**Closed by xtekky** 2023-04-21 09:39 UTC

**Comment by wangjiegui** [comment] 2023-04-21 09:43
email canivas940@fitzola.com
send_code {'data': {'sendVerificationCode': {'status': 'user_with_confirmed_email_not_found', 'errorMessage': None}}, 'extensions': {'is_final': True}}
code 587104
verify_code {'data': None, 'errors': [{'message': 'Server Error'}], 'extensions': {'is_final': True}}
{'data': None, 'errors': [{'message': 'Server Error'}], 'extensions': {'is_final': True}}
